/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package staff_manager;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author oOOo
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private static JFrame f;
    private static String DB_URL = "jdbc:sqlserver://localhost:1433;"
            + "databaseName=vd_java;"
            + "integratedSecurity=true";
    private static String USER_NAME = "sa";
    private static String PASSWORD = "1234567";
    private static JTextField text_user, text_pass;
    private static int flag = 0;

    public static void main(String[] args) {

        f = new JFrame("dang nhap");
        f.setSize(300, 200);
        JPanel p = new JPanel();
        p.setSize(200, 200);
        p.setLayout(new GridLayout(2, 2, 30, 30));
        JLabel la_user = new JLabel("nhap user");
        la_user.setSize(50, 10);
        JLabel la_pass = new JLabel("nhap password");
        la_pass.setSize(50, 10);
        text_user = new JTextField("", 200);
        text_pass = new JTextField("", 200);

        p.add(la_user);
        p.add(text_user);
        p.add(la_pass);
        p.add(text_pass);
        JButton bt_dn = new JButton("Dang nhap");
        bt_dn.setSize(10, 10);
        JButton bt_dk = new JButton("Dang ky");
        bt_dk.setSize(10, 10);
        JPanel p1 = new JPanel();
        p1.setLayout(new FlowLayout(1, 10, 20));
        p1.add(bt_dn);
        p1.add(bt_dk);
        f.setLayout(new BorderLayout(10, 10));
        f.add(p, BorderLayout.CENTER);
        f.add(p1, BorderLayout.SOUTH);
        f.setVisible(true);
    }
    
    public void actionPerform(ActionEvent e) {
        try {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            } catch (Exception ex) {

            }
            Connection conn = DriverManager.getConnection(DB_URL, USER_NAME, PASSWORD);
            Statement sta = (Statement) conn.createStatement(); 
            ResultSet rs = sta.executeQuery("select * from tai_khoan");
            
        } catch (Exception ex) {
            
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
